baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Blog'

license = "MIT"
licenselink = "https://github.com/otavio.cat/otavio.cat/blob/master/LICENSE"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.128.0"
